NAME = minishell

src = bulit.c execution.c re_libft.c small_libft.c split.c split_with_slash.c utils1.c utils2.c  main.c
run : 
	gcc -lreadline $(src) -o $(NAME) -fsanitize=address -g3
	./minishell

